name: xwidget_builder
description: "Development tool for generating XWidget components to build dynamic Flutter UIs with XML based markup."
version: 0.1.1
repository: https://github.com/appfluent/xwidget_builder
issue_tracker: https://github.com/appfluent/xwidget_builder/issues

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^7.7.1
  args: ^2.4.2
  flutter:
    sdk: flutter
  glob: ^2.1.3
  markdown: ^7.3.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  test: ">=1.25.15 <1.28.0"

flutter:

